# Generated by Django 5.0.6 on 2024-06-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_attendance', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
